# Generated by Django 5.2.8 on 2025-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('notices', '0005_noticecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_notices',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='notices.notice'),
        ),
    ]
