# Generated by Django 5.2.8 on 2025-12-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_saved_notices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_notices',
        ),
    ]
