# Generated by Django 5.2.8 on 2025-12-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('event', 'Event'), ('urgent', 'Urgent')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
    ]
