# Generated by Django 5.2.8 on 2025-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_saved_notices'),
        ('notices', '0005_noticecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_notices', to='core.profile'),
        ),
    ]
